version: '3.9'

services:

  mongo:
    image: mongo:3.6.21
    volumes:
      - mongodb-lib:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: pasaword
    ports:
      - "27017:27017"

  mysqldb:
    image: mysql:5.7
    volumes:
      - mysql-lib:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pasaword
      MYSQL_DATABASE: mybase
    ports:
      - "3306:3306"

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=pasaword
      - REDIS_PORT_NUMBER=6379
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
    ports:
      - '6379:6379'
    volumes:
      - redis-conf:/opt/bitnami/redis/mounted-etc/redis.con
      - redis-persistence:/bitnami/redis/data

  rabbitmq:
    image: 'rabbitmq:3-management'
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pasaword
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 20s
      retries: 5

volumes:
  mongodb-lib:
  mysql-lib:
  redis-conf:
  redis-persistence:
  rabbitmq-data:
  rabbitmq-log:
