# All services configuration

  prod:
    database:
      mongo:
        host: localhost
        port: 27017
        user: app
        password: pasaword
        databaseName: parser_telegram
        collectionMessage: messages
        collectionChannel: channels
        collectionDelivery: delivery

      mysql:
        host: localhost
        port: 3306
        user: xxx
        password:  pasaword
        databaseName: parser_telegram

      redis:
        host: localhost
        port: 6379
        password: pasaword

    rabbitmq:
      host: localhost
      portApp: 5672
      portAdmin: 15672
      user: guest
      password: guest
      queue: telegram-parser.event-bus.queue
      routingKey: telegram-parse
      exchange: telegram-parser.event-bus.exchange
      batchSize: 100

  test:
    database:
      mongo:
        host: localhost
        port: 27017
        user: app
        password: pasaword
        databaseName: parser_telegram
        collectionMessage: messages
        collectionChannel: channels
        collectionDelivery: delivery

      mysql:
        host: localhost
        port: 3306
        user: user
        password: pasaword
        databaseName: parser_telegram

      redis: #redis-cli -h localhost -p 6379 -a pasaword
        host: localhost
        port: 6379
        password: pasaword

    rabbitmq:
      host: localhost
      portApp: 5672
      portAdmin: 15672
      user: user
      password: pasaword
      queue: telegram-parser.event-bus.queue
      routingKey: telegram-parse
      exchange: telegram-parser.event-bus.exchange
      batchSize: 100
