# Application
appName: TelegramParser

# Telegram API
telegram:
  api_id: 17436154
  api_hash: e54c86627e6fed51dd4c548dfc920094
  phone: +375293372269
  password: Pasawordas123
  name_connection: session_name

  proxy:
    proxy_type: SOCKS5  # (mandatory) protocol to use (see above)
    addr: 184.95.235.194      # (mandatory) proxy IP address
    port: 1080         # (mandatory) proxy port number
    username: foo      # (optional) username if the proxy requires auth
    password: bar     # (optional) password if the proxy requires auth
    rdns: True